apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgAOrGmcfYM467CwhryhV6AEAVBb6WD+z+69L4Bn67WNlSMN12b+BeE/n/sc196t4PvRdqVuQ2EmM5m21L6+ZG/d3Qzs9+ijZNf/u5hJ1lcuSMB56VjOrTKrrE0MVaKhwhOUO/DVtlS99z7nIBpXkYtLShR4jERFcretselBQYyqngCldtHBsU2Z9nOjqF9VTj+D91r7lrToycp2hYhYocH4rd5hi0K1q2vao3c+mFw5Di2kpgGKd5f4D9TewcUqGXyiE82pq66TvmYSFs6YLQVEPqL9tWM7T4aVdrQVO6QiUcDZzws/nOGbCojRuXyFPCZ3Mp0wnh0+fbcm/RREfOQAtYsWNTc67DGV4mvk2zBuo0zrIiruOjfAWTWqfbfCGY/WdD9HtQcDnJJDdQUMCqkHmxJZCoi8F2NUig+GAuTfSLnKd4fe58QZOP81kl49QvTfjhbBncyo6TGPcgnwmlZNusDcChQb1kc+6oIc10AdnCJ/GI8MVzrmXFRJrr35txiiVqbFyerHfvVDefiHyjB8RK7FxfA2d7AgJQt8wwP+gcNlqIlA5ySFXEFG56hSiHoSIwzffCiKnfDqLIaRShhq9o4qKJWKbywpO+Ll5/MaLjwzyIH9mscDVPDrcatmAr8lo5tmmhZaKzx59Lh8TFxruxJMA1u1F9KZgEk/j3UQ3kKn4x0wFqugqIhCT77F6EnacNynqrYRgk9NvILyS84+8BjUhSUymN3rRTYzYndG+eXTpwv7n58j3nf1zqxhDW+KDvpWSkHy2ECMIrVu6HV0WTacWPjL6uFwbKRz7+q0LyE=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: monitoring
    type: Opaque

